spring.application.name=Ecomm-app
#spring.h2.console.enabled=true

#spring.datasource.url=jdbc:h2:mem:testdb
#spring.datasource.driverClassName=org.h2.Driver
#spring.datasource.username=sa
#spring.datasource.password=

product.images.dir = images

# MySQL properties
spring.datasource.url=jdbc:mysql://localhost:3306/ecommerce
#spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=XXXXXX
spring.datasource.password=XXXXXX

spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

#Below property alters how Springboot runs ...
#default order > application start > run data.sql > Hibernate starts and create tables
# this avoids running of script even befor hbernate creat table
spring.jpa.defer-datasource-initialization=true

#spring.jpa.hibernate.ddl-auto=update
#spring.jpa.show-sql=true
#spring.jpa.properties.hibernate.format_sql=true
